[tool.poetry]
name = "neo4j-movie-recommender"
packages = [
    { include = "neo4j_movie_recommender" }
]
version = "0.1.0"
description = "Build a semantic layer to allow an agent to interact with a graph database in consistent and robust way."
authors = [
    "Prashanth Baskar <baskar.pr@northeastern.edu>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.353,<0.2"
openai = "<2"
neo4j = "^5.14.0"


[tool.langserve]
export_module = "neo4j_movie_recommender"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "semantic_layer"
author = "Neo4j"
integrations = ["Neo4j", "OpenAI"]
tags = ["search", "graph-database", "function-calling"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
