[tool.poetry]
name = "movie-agent-recommender"
version = "0.1.0"
description = ""
authors = ["Prashanth Baskar <baskar.pr@northeastern.edu>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
neo4j-movie-recommender = {path = "packages/neo4j-semantic-layer", develop = true}
httpx = "<0.26"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
